# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('nconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.DateField(verbose_name=b'Year of birth')),
                ('death_year', models.DateField(verbose_name=b'Year of death')),
                ('primary_profession', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movie_type', models.CharField(max_length=20)),
                ('primary_title', models.CharField(max_length=1000)),
                ('original_title', models.CharField(max_length=1000)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(null=True)),
                ('length', models.IntegerField(verbose_name=b'Runtime (minutes)')),
                ('genres', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='rest_api.Movie'),
        ),
    ]
