# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(null=True, verbose_name=b'Runtime (minutes)'),
        ),
    ]
