# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190427_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='start_year',
            field=models.DateField(null=True),
        ),
    ]
